<?php
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Messenger\MessengerInterface;
    
/**
 * Implements hook_views_pre_view().
 *
 */
function umd_cmns_views_pre_view(\Drupal\views\ViewExecutable $view, $display_id, array $args) {
  if ($view->id() === 'news' && ($display_id === 'block_4' || $display_id === 'block_7' || $display_id === 'block_11')) {  
  	// look up node to see if primary tag exists
  	$node = \Drupal::request()->attributes->get('node');

  	// return on bad request
  	if (!$node) { return; }
  	
  	$node = \Drupal\node\Entity\Node::load($node->id());
  	// perform check only on content type page
  	if ($node->getType() == 'page') {
			$primary_tag_id = $node->get('field_primary_tag')->getValue();		
			// set contextual filter as page's primary tag		
  		if ($primary_tag_id) {
      	$args[0] = $primary_tag_id[0]['target_id'];
      	$view->setArguments($args);  	
  		} 
		} else {
			// related news for team members
  		if ($node->getType() == 'team') {
  			$team_name_tag_id = $node->get('field_user_group')->getValue();
				// set contextual filter as page's primary tag		
  			if ($team_name_tag_id) {
      		$args[0] = $team_name_tag_id[0]['target_id'];
      		$view->setArguments($args);  	
  			}
  		}
  	} 			
  }

  if ($view->id() === 'team' && ($view->displayHandlers->get($view->current_display)->getPluginId() == 'block')) {  
  
  	// look up node to see if primary tag exists
  	$node = \Drupal::request()->attributes->get('node');

  	// return on bad request
  	if (!$node) { return; }
  	
  	$node = \Drupal\node\Entity\Node::load($node->id());
  	// perform check only on content type page
  	if ($node->getType() == 'page') {		
			// check to make sure primary_tag field exists
  		if ($node->hasField('field_primary_tag')) {
				$primary_tag_id = $node->get('field_primary_tag')->getValue();		
				// set contextual filter as page's primary tag		
  			if ($primary_tag_id) {
      		$args[0] = $primary_tag_id[0]['target_id'];
      		$view->setArguments($args);  	
  			}    		  		
  		}	
  	}
  }    
}

/* switch sort for events if they are upcoming or past */
function umd_cmns_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'event') {
    if ($view->current_display == 'block_4') {
      // First we look to see if there's an exposed filter selected.
      $view_past_events = FALSE;
      if (isset($view->exposed_raw_input)) {
        foreach ($view->exposed_raw_input as $filter_key => $filter_value) {
          if ($filter_key == 'event_status' && $filter_value == 2) {
            $view_past_events = TRUE;
          }
        }
      }      
      // If the view is filtered then we alter the sort order
      if ($view_past_events && isset($view->query->orderby)) {
     		$view->query->orderby[0]['direction'] = 'DESC';
      }
    }
  }
}

/**
 * Implements hook_cron().
 */
function umd_cmns_cron() {      
  \Drupal::service('umd_cmns.cmns_helper')->unpublishFacultyTags();

  // Log message:
  \Drupal::messenger()->addStatus('umd_cmns_cron() was executed.');
}