<?php
use Drupal\views\ViewExecutable;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Messenger\MessengerInterface;
    
/**
 * Implements hook_views_pre_view().
 *
 */
function umd_cmns_views_pre_view(\Drupal\views\ViewExecutable $view, $display_id, array $args) {
  if ($view->id() === 'news' && ($display_id === 'block_4' || $display_id === 'block_7')) {  
  	// look up node to see if primary tag exists
  	$node = \Drupal::request()->attributes->get('node');

  	// return on bad request
  	if (!$node) { return; }
  	
  	$node = \Drupal\node\Entity\Node::load($node->id());
  	// perform check only on content type page
  	if ($node->getType() == 'page') {
			$primary_tag_id = $node->get('field_primary_tag')->getValue();		
			// set contextual filter as page's primary tag		
  		if ($primary_tag_id) {
      	$args[0] = $primary_tag_id[0]['target_id'];
      	$view->setArguments($args);  	
  		} 
		} else {
			// related news for team members
  		if ($node->getType() == 'team') {
  			$team_name_tag_id = $node->get('field_user_group')->getValue();
				// set contextual filter as page's primary tag		
  			if ($team_name_tag_id) {
      		$args[0] = $team_name_tag_id[0]['target_id'];
      		$view->setArguments($args);  	
  			}
  		}
  	} 			
  }

  if ($view->id() === 'team' && ($display_id === 'block_4' || $display_id === 'block_6' || $display_id === 'block_7')) {  
  	// look up node to see if primary tag exists
  	$node = \Drupal::request()->attributes->get('node');

  	// return on bad request
  	if (!$node) { return; }
  	
  	$node = \Drupal\node\Entity\Node::load($node->id());
  	// perform check only on content type page
  	if ($node->getType() == 'page') {
			$primary_tag_id = $node->get('field_primary_tag')->getValue();		
			// set contextual filter as page's primary tag		
  		if ($primary_tag_id[0]['target_id']) {
      	$args[0] = $primary_tag_id[0]['target_id'];
      	$view->setArguments($args);  	
  		}  	
  	}
  }    
}

/**
 * Implements hook_cron().
 */
function umd_cmns_cron() {      
  \Drupal::service('umd_cmns.cmns_helper')->unpublishFacultyTags();

  // Log message:
  \Drupal::messenger()->addStatus('umd_cmns_cron() was executed.');
}